# Generated by Django 6.0.2 on 2026-03-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meow_sync_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('playlist_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='meow_sync_app.playlistsynchronization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_sync_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='playlistsynchronization',
            name='commenters',
            field=models.ManyToManyField(related_name='commented_playlist_syncs', through='meow_sync_app.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
