# Generated by Django 6.0.2 on 2026-03-18 16:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('meow_sync_app', '0002_comment_playlistsynchronization_commenters'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='oauthconnection',
			name='provider_user_id',
			field=models.CharField(default='not-set', max_length=255),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='comment',
			name='user',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='playlist_sync_comment',
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.AlterField(
			model_name='oauthconnection',
			name='refresh_token',
			field=models.CharField(default='not-set', max_length=255),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='oauthconnection',
			name='token_expires_at',
			field=models.DateTimeField(
				default=datetime.datetime(2026, 3, 18, 16, 40, 53, 519079)
			),
			preserve_default=False,
		),
	]
