# Generated by Django 6.0.4 on 2026-04-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('meow_sync_app', '0006_alter_songidtranslation_spotify_id_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='oauthconnection',
			name='access_token',
			field=models.TextField(),
		),
		migrations.AlterField(
			model_name='oauthconnection',
			name='refresh_token',
			field=models.TextField(),
		),
	]
