name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  django-ci:
    uses: ./.github/workflows/reusable-django-ci.yaml

  vue-ci:
    uses: ./.github/workflows/reusable-vue-ci.yaml

  deployment:
    uses: ./.github/workflows/reusable-cd.yaml
    concurrency: production
    needs: [django-ci, vue-ci]
    if: always() && github.ref == 'refs/heads/main'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
