name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHON_VERSION: '3.14.3'
  UV_VERSION: '0.10.4'


jobs:
  django-ci:
    uses: ./.github/workflows/reusable-django-ci.yaml

  vue-ci:
    uses: ./.github/workflows/reusable-vue-ci.yaml

  deployment:
    uses: ./.github/workflows/reusable-cd.yaml
    needs: [django-ci, vue-ci]
    if: github.ref == 'refs/heads/19-create-cd-pipeline'

