name: "Deploy to production"

on:
  workflow_call:


jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Say hello
        run: echo "Hello"
